/// Returns `true` if the given OS name belongs to a desktop OS family.
///
/// Derived from Matomo's `OperatingSystem::$desktopOsArray` and `$osFamilies`.
/// Comparison is case-insensitive because OS names may come from regex captures.
pub(crate) fn is_desktop_os(os_name: &str) -> bool {
    // All comparisons are lowercase. The allocation is fine here since this
    // only runs when no device brand was matched.
    matches!(
        os_name.to_ascii_lowercase().as_str(),
        // AmigaOS family
        "amigaos" | "aros" | "morphos"
        // IBM family
        | "arcaos" | "os/2"
        // GNU/Linux family
        | "aosc os"
        | "asplinux"
        | "alpine linux"
        | "amazon linux"
        | "arch linux"
        | "azure linux"
        | "backtrack"
        | "brightsignos"
        | "caixa magica"
        | "centos"
        | "centos stream"
        | "china os"
        | "clear linux os"
        | "coolita os"
        | "dvkbuntu"
        | "debian"
        | "deepin"
        | "euleros"
        | "fritz!os"
        | "fedora"
        | "fenix"
        | "foresight linux"
        | "freebox"
        | "fuchsia"
        | "gnu/linux"
        | "gentoo"
        | "hascodingos"
        | "joli os"
        | "kali"
        | "kanotix"
        | "knoppix"
        | "kreatv"
        | "kubuntu"
        | "lindowsos"
        | "linpus"
        | "linspire"
        | "liri os"
        | "loongnix"
        | "lubuntu"
        | "lumin os"
        | "mageia"
        | "mandriva"
        | "mint"
        | "motorola ezx"
        | "nova"
        | "openvz"
        | "openwrt"
        | "opera tv"
        | "oracle linux"
        | "ordissimo"
        | "pclinuxos"
        | "pardus"
        | "plasma mobile"
        | "proxmox ve"
        | "pureos"
        | "qtopia"
        | "raspberry pi os"
        | "raspbian"
        | "red hat"
        | "red star"
        | "redos"
        | "rocky linux"
        | "roku os"
        | "rosa"
        | "routeros"
        | "suse"
        | "sabayon"
        | "sailfish os"
        | "scientific linux"
        | "serenityos"
        | "slackware"
        | "tencentos"
        | "tivo os"
        | "tmaxos"
        | "turbolinux"
        | "uos"
        | "ubuntu"
        | "vidaa"
        | "vectorlinux"
        | "vizios"
        | "webian"
        | "wophone"
        | "xubuntu"
        | "zenwalk"
        | "zorinos"
        | "blackpanther os"
        | "elementary os"
        | "gnewsense"
        | "moonos"
        | "opensuse"
        // Mac family
        | "mac"
        // Unix family
        | "aix"
        | "bsd"
        | "dragonfly"
        | "electrobsd"
        | "freebsd"
        | "genix"
        | "ghostbsd"
        | "hp-ux"
        | "irix"
        | "inferno"
        | "minix"
        | "news-os"
        | "nextstep"
        | "netbsd"
        | "osf1"
        | "openbsd"
        | "plan 9"
        | "solaris"
        | "star-blade os"
        | "syllable"
        | "ultrix"
        // Windows family
        | "windows"
        // BeOS family
        | "beos" | "haiku os"
        // Chrome OS family
        | "chrome os" | "chromium os" | "fydeos" | "seewoos"
        // OpenVMS family
        | "openvms"
    )
}

/// Returns `true` if the given OS name belongs to the Android OS family.
///
/// Derived from Matomo's `OperatingSystem::$osFamilies['Android']`.
pub(crate) fn is_android_os(os_name: &str) -> bool {
    matches!(
        os_name,
        "Android"
            | "Android TV"
            | "Armadillo OS"
            | "Baidu Yi"
            | "Bliss OS"
            | "ClearOS Mobile"
            | "CyanogenMod"
            | "Fire OS"
            | "GridOS"
            | "HarmonyOS"
            | "HELIX OS"
            | "LeafOS"
            | "Lineage OS"
            | "Meta Horizon"
            | "MildWild"
            | "MocorDroid"
            | "OpenHarmony"
            | "PICO OS"
            | "Puffin OS"
            | "RazoDroiD"
            | "Remix OS"
            | "Resurrection Remix OS"
            | "Revenge OS"
            | "risingOS"
            | "Sirin OS"
            | "Smartisan OS"
            | "Wear OS"
            | "YunOS"
    )
}
